# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import gameplay.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20180623_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False, verbose_name=gameplay.models.Game),
        ),
    ]
